// DEFINEM QUAL BIBLIOTECAS IREMOS UTILIZAR
// OS OUTROS NAMESPACE PODEM SER IMPORTADOS ATRAVES DOS USING, SENDO ELES INTERNOS OU EXTERNOS
// POR PADRÃO SÓ VEM INCLUSO O BÁSICO, AS OUTRAS COISAS PRECISAM SER IMPORTADAS
using System;

// NAMESPACE SÃO AS AS DIVISÕES LÓGICAS 
// NÃO PODEMOS TER DUAS CLASSES COM O MESMO NOME EM UM ÚNICO NAMESPACE
// UM NAMESPACE PODE SER REUTILIZADO EM DIVERSOS ARQUIVOS
namespace Aula01
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
